name:                "jevko"
version:             "0.1.0.0"
github:              "lgastako/jevko"
license:             "BSD3"
author:              "John Evans"
maintainer:          "lgastako@gmail.com"
copyright:           "2022 John Evans"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            Jevko Parser
category:            Text, Web

description:         "README at <https://github.com/lgastako/jevko#readme>"

dependencies:
- attoparsec
- base               >= 4.7 && < 5
- text

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  jevko:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - jevko

tests:
  jevko-test:
    main:                Driver.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - jevko
    - tasty
    - tasty-discover
    - tasty-hspec
    - tasty-quickcheck
